<?php
/**
 *  Copyright © Above The Fray Design, Inc. All rights reserved.
 *  See ATF_COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Squiz.PHP.GlobalKeyword.NotAllowed
?>
<?php
    /** @var Tax $block */
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $this->helper(\Magento\Tax\Helper\Data::class)->getCalculatedTaxes($_source);
    global $taxIter;
    $taxIter++;

    use ATF\Zamp\ViewModel\TaxViewModel;
    use Magento\Framework\Escaper;
    use Magento\Tax\Block\Sales\Order\Tax;

    /** @var Escaper $escaper */
    /** @var TaxViewModel $taxViewModel */
    $taxViewModel = $block->getData('view_model');
    $taxLabel = $taxViewModel->getTaxLabel($block->getOrder(), 'Tax');
?>

<?php if ($_fullInfo && $block->displayFullSummary()): ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $title      = $info['title'];
            ?>
            <tr class="totals tax details details-<?= (int)$taxIter ?><?= ($block->getIsPlaneMode())? ' plane' : '' ?>">
                <td <?= /* @noEscape */ $block->getLabelProperties() ?>>
                    <?= $escaper->escapeHtml($title) ?>
                    <?php if ($percent !== null): ?>
                        (<?= (float) $percent ?>%)
                    <?php endif; ?>
                    <br />
                </td>
                <td <?= /* @noEscape */ $block->getValueProperties() ?> rowspan="1">
                    <?= /* @noEscape */ $_order->formatPrice($amount) ?>
                </td>
            </tr>
        <?php endforeach; ?>
<?php endif; ?>

<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary plane">
<?php else: ?>
<tr class="totals-tax asd">
<?php endif; ?>
    <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
        <?php if ($block->displayFullSummary()): ?>
            <div class="detailed"><?= $escaper->escapeHtml($taxLabel) ?></div>
        <?php else: ?>
            <?= $escaper->escapeHtml($taxLabel) ?>
        <?php endif; ?>
    </th>
    <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $escaper->escapeHtmlAttr($taxLabel) ?>">
        <?= /* @noEscape */ $_order->formatPrice($_source->getTaxAmount()) ?>
    </td>
</tr>
