<?php
/**
 * Copyright © Above The Fray Design, Inc. All rights reserved.
 * See ATF_COPYING.txt for license details.
 */

/** @var $block \Magento\Backend\Block\Template */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "ATF_Zamp/js/grid/buttons": {
                "listingNamespace": "zamp_historical_transaction_sync_listing",
                "syncButtonSelector": ".transaction-sync",
                "searchButtonSelector": ".transaction-search"
            }
        }
    }
</script>
