<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\Invoice\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php $invoice = $block->getInvoice() ?>

<?php if ($zampId = $invoice->getZampTransactionId()): ?>

    <?php $html = <<<HTML
    <tr>
        <th>{$escaper->escapeHtml(__('Zamp ID'))}</th>
        <td>{$escaper->escapeHtml($zampId)}</td>
    </tr>
HTML;
    ?>

    <?php $scriptString = <<<script
    require(["jquery"], function($) {
        $(".invoice-view-information .invoice-information-table tbody").append("{$escaper->escapeJs($html)}");
    });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php endif;
